export const CourseABI = [
  // Read functions
  { type: "function", name: "ydToken", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "courseCounter", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "categoryCounter", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "platformFeePercent", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "refundPeriod", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "referralRewardPercent", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "monthlySubscriptionPrice", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "yearlySubscriptionPrice", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "bulkDiscountThreshold", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "bulkDiscountPercent", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "requireCertification", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },

  { type: "function", name: "courses", inputs: [{ name: "courseId", type: "uint256" }], outputs: [
    { name: "id", type: "uint256" },
    { name: "title", type: "string" },
    { name: "description", type: "string" },
    { name: "coverUrl", type: "string" },
    { name: "priceYDT", type: "uint256" },
    { name: "instructor", type: "address" },
    { name: "isActive", type: "bool" },
    { name: "createdAt", type: "uint256" },
    { name: "totalStudents", type: "uint256" },
    { name: "categoryId", type: "uint256" },
    { name: "totalRating", type: "uint256" },
    { name: "ratingCount", type: "uint256" },
  ], stateMutability: "view" },

  { type: "function", name: "categories", inputs: [{ name: "categoryId", type: "uint256" }], outputs: [
    { name: "id", type: "uint256" },
    { name: "name", type: "string" },
    { name: "isActive", type: "bool" },
  ], stateMutability: "view" },

  { type: "function", name: "hasPurchased", inputs: [{ name: "courseId", type: "uint256" }, { name: "user", type: "address" }], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "certifiedInstructors", inputs: [{ name: "instructor", type: "address" }], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "referralRewards", inputs: [{ name: "user", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },

  { type: "function", name: "subscriptions", inputs: [{ name: "user", type: "address" }], outputs: [
    { name: "startTime", type: "uint256" },
    { name: "endTime", type: "uint256" },
    { name: "isActive", type: "bool" },
  ], stateMutability: "view" },

  { type: "function", name: "purchaseRecords", inputs: [{ name: "courseId", type: "uint256" }, { name: "user", type: "address" }], outputs: [
    { name: "courseId", type: "uint256" },
    { name: "purchaseTime", type: "uint256" },
    { name: "pricePaid", type: "uint256" },
    { name: "refunded", type: "bool" },
    { name: "referrer", type: "address" },
  ], stateMutability: "view" },

  { type: "function", name: "courseRatings", inputs: [{ name: "courseId", type: "uint256" }, { name: "user", type: "address" }], outputs: [
    { name: "score", type: "uint8" },
    { name: "comment", type: "string" },
    { name: "timestamp", type: "uint256" },
  ], stateMutability: "view" },

  { type: "function", name: "getCourse", inputs: [{ name: "_courseId", type: "uint256" }], outputs: [{ name: "", type: "tuple", components: [
    { name: "id", type: "uint256" },
    { name: "title", type: "string" },
    { name: "description", type: "string" },
    { name: "coverUrl", type: "string" },
    { name: "priceYDT", type: "uint256" },
    { name: "instructor", type: "address" },
    { name: "isActive", type: "bool" },
    { name: "createdAt", type: "uint256" },
    { name: "totalStudents", type: "uint256" },
    { name: "categoryId", type: "uint256" },
    { name: "totalRating", type: "uint256" },
    { name: "ratingCount", type: "uint256" },
  ]}], stateMutability: "view" },

  { type: "function", name: "getActiveCourses", inputs: [{ name: "_offset", type: "uint256" }, { name: "_limit", type: "uint256" }], outputs: [{ name: "", type: "tuple[]", components: [
    { name: "id", type: "uint256" },
    { name: "title", type: "string" },
    { name: "description", type: "string" },
    { name: "coverUrl", type: "string" },
    { name: "priceYDT", type: "uint256" },
    { name: "instructor", type: "address" },
    { name: "isActive", type: "bool" },
    { name: "createdAt", type: "uint256" },
    { name: "totalStudents", type: "uint256" },
    { name: "categoryId", type: "uint256" },
    { name: "totalRating", type: "uint256" },
    { name: "ratingCount", type: "uint256" },
  ]}], stateMutability: "view" },

  { type: "function", name: "getCoursesByCategory", inputs: [{ name: "_categoryId", type: "uint256" }, { name: "_offset", type: "uint256" }, { name: "_limit", type: "uint256" }], outputs: [{ name: "", type: "tuple[]", components: [
    { name: "id", type: "uint256" },
    { name: "title", type: "string" },
    { name: "description", type: "string" },
    { name: "coverUrl", type: "string" },
    { name: "priceYDT", type: "uint256" },
    { name: "instructor", type: "address" },
    { name: "isActive", type: "bool" },
    { name: "createdAt", type: "uint256" },
    { name: "totalStudents", type: "uint256" },
    { name: "categoryId", type: "uint256" },
    { name: "totalRating", type: "uint256" },
    { name: "ratingCount", type: "uint256" },
  ]}], stateMutability: "view" },

  { type: "function", name: "getStudentCourses", inputs: [{ name: "_student", type: "address" }], outputs: [{ type: "uint256[]" }], stateMutability: "view" },
  { type: "function", name: "getInstructorCourses", inputs: [{ name: "_instructor", type: "address" }], outputs: [{ type: "uint256[]" }], stateMutability: "view" },
  { type: "function", name: "hasUserPurchased", inputs: [{ name: "_courseId", type: "uint256" }, { name: "_user", type: "address" }], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "getCourseAverageRating", inputs: [{ name: "_courseId", type: "uint256" }], outputs: [{ name: "average", type: "uint256" }, { name: "count", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "hasActiveSubscription", inputs: [{ name: "_user", type: "address" }], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "getPurchaseRecord", inputs: [{ name: "_courseId", type: "uint256" }, { name: "_student", type: "address" }], outputs: [{ name: "", type: "tuple", components: [
    { name: "courseId", type: "uint256" },
    { name: "purchaseTime", type: "uint256" },
    { name: "pricePaid", type: "uint256" },
    { name: "refunded", type: "bool" },
    { name: "referrer", type: "address" },
  ]}], stateMutability: "view" },
  { type: "function", name: "getUserRating", inputs: [{ name: "_courseId", type: "uint256" }, { name: "_user", type: "address" }], outputs: [{ name: "", type: "tuple", components: [
    { name: "score", type: "uint8" },
    { name: "comment", type: "string" },
    { name: "timestamp", type: "uint256" },
  ]}], stateMutability: "view" },

  // Write functions
  { type: "function", name: "createCourse", inputs: [
    { name: "_title", type: "string" },
    { name: "_description", type: "string" },
    { name: "_coverUrl", type: "string" },
    { name: "_priceYDT", type: "uint256" },
    { name: "_categoryId", type: "uint256" },
  ], outputs: [{ type: "uint256" }], stateMutability: "nonpayable" },

  { type: "function", name: "purchaseCourse", inputs: [{ name: "_courseId", type: "uint256" }, { name: "_referrer", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "purchaseCoursesBulk", inputs: [{ name: "_courseIds", type: "uint256[]" }, { name: "_referrer", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "requestRefund", inputs: [{ name: "_courseId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "rateCourse", inputs: [{ name: "_courseId", type: "uint256" }, { name: "_score", type: "uint8" }, { name: "_comment", type: "string" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "purchaseMonthlySubscription", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "purchaseYearlySubscription", inputs: [], outputs: [], stateMutability: "nonpayable" },

  { type: "function", name: "updateCourse", inputs: [
    { name: "_courseId", type: "uint256" },
    { name: "_title", type: "string" },
    { name: "_description", type: "string" },
    { name: "_coverUrl", type: "string" },
    { name: "_priceYDT", type: "uint256" },
    { name: "_categoryId", type: "uint256" },
  ], outputs: [], stateMutability: "nonpayable" },

  { type: "function", name: "deactivateCourse", inputs: [{ name: "_courseId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },

  // Owner functions
  { type: "function", name: "createCategory", inputs: [{ name: "_name", type: "string" }], outputs: [{ type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "updateCategory", inputs: [{ name: "_categoryId", type: "uint256" }, { name: "_name", type: "string" }, { name: "_isActive", type: "bool" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "certifyInstructor", inputs: [{ name: "_instructor", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "decertifyInstructor", inputs: [{ name: "_instructor", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setRequireCertification", inputs: [{ name: "_required", type: "bool" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setPlatformFee", inputs: [{ name: "_feePercent", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setRefundPeriod", inputs: [{ name: "_period", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setReferralRewardPercent", inputs: [{ name: "_percent", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setSubscriptionPrices", inputs: [{ name: "_monthlyPrice", type: "uint256" }, { name: "_yearlyPrice", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setBulkDiscountSettings", inputs: [{ name: "_threshold", type: "uint256" }, { name: "_discountPercent", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address" }], outputs: [], stateMutability: "nonpayable" },

  // Events
  { type: "event", name: "CourseCreated", inputs: [{ name: "courseId", type: "uint256", indexed: true }, { name: "title", type: "string", indexed: false }, { name: "instructor", type: "address", indexed: true }, { name: "priceYDT", type: "uint256", indexed: false }, { name: "categoryId", type: "uint256", indexed: false }] },
  { type: "event", name: "CoursePurchased", inputs: [{ name: "courseId", type: "uint256", indexed: true }, { name: "student", type: "address", indexed: true }, { name: "priceYDT", type: "uint256", indexed: false }, { name: "timestamp", type: "uint256", indexed: false }, { name: "referrer", type: "address", indexed: false }] },
  { type: "event", name: "CourseUpdated", inputs: [{ name: "courseId", type: "uint256", indexed: true }, { name: "title", type: "string", indexed: false }, { name: "priceYDT", type: "uint256", indexed: false }] },
  { type: "event", name: "CourseDeactivated", inputs: [{ name: "courseId", type: "uint256", indexed: true }] },
  { type: "event", name: "CourseRated", inputs: [{ name: "courseId", type: "uint256", indexed: true }, { name: "student", type: "address", indexed: true }, { name: "score", type: "uint8", indexed: false }, { name: "comment", type: "string", indexed: false }] },
  { type: "event", name: "RefundIssued", inputs: [{ name: "courseId", type: "uint256", indexed: true }, { name: "student", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }] },
  { type: "event", name: "SubscriptionPurchased", inputs: [{ name: "user", type: "address", indexed: true }, { name: "duration", type: "uint256", indexed: false }, { name: "endTime", type: "uint256", indexed: false }] },
  { type: "event", name: "ReferralRewardPaid", inputs: [{ name: "referrer", type: "address", indexed: true }, { name: "referee", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }] },
  { type: "event", name: "InstructorCertified", inputs: [{ name: "instructor", type: "address", indexed: true }] },
  { type: "event", name: "InstructorDecertified", inputs: [{ name: "instructor", type: "address", indexed: true }] },
  { type: "event", name: "CategoryCreated", inputs: [{ name: "categoryId", type: "uint256", indexed: true }, { name: "name", type: "string", indexed: false }] },
  { type: "event", name: "CategoryUpdated", inputs: [{ name: "categoryId", type: "uint256", indexed: true }, { name: "name", type: "string", indexed: false }] },
  { type: "event", name: "OwnershipTransferred", inputs: [{ name: "previousOwner", type: "address", indexed: true }, { name: "newOwner", type: "address", indexed: true }] },
] as const;
